# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SRGTimeCheatCapturerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SRGTimeCheatCapturerDemo
  pod 'Reachability'
  pod 'SRGTimeCheatCapturer', :path => '../'

  target 'SRGTimeCheatCapturerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
